### ISSUE TITLE
윈도우 8.1에서 사이트가 뜨지않음(제목 수정됨)

### ISSUE THREAD

**Issue by Xenon2000** [CirnoV/KanColleViewer#123]
제가 윈도우 8.1에서 만 확인하여서 죄송합니다만, 윈도우 8.1 기준으로 실행이 아예 불가능한 오류가 있습니다.
Auto Update 뜨기도 전에 오류로 꺼져버립니다.
자세한것은 직접 확인해 주시기 바랍니다.

**Comment by WolfgangKurz** [comment]
에러로그라도 첨부해주세요

**Comment by Xenon2000** [comment]
한번 실행하니 4개의 오류파일이 생성되어 4개를 전부 올려드립니다.

---------------------1-----------------------
*** Error Report (Dispatcher) ***
KanColleViewer ver.4.5.0 rev.2
2018-09-20 오후 1:22:57 +09:00

SystemEnvironment
OS:           Microsoft Windows 8.1 Enterprise K
OSVersion:    6.3.9600
Architecture: 64비트
Runtime:      .NET Framework Version: 4.7.1

CPU:         Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
RAM (Total): 8,068,572 KB
RAM (Free):  5,207,120 KB

Sender:    System.Windows.Threading.Dispatcher
Exception: System.IO.FileNotFoundException

System.IO.FileNotFoundException: 파일이나 어셈블리 'CefSharp.Core.dll' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다.
파일 이름: 'CefSharp.Core.dll'
   위치: Grabacr07.KanColleViewer.Application.CefInitialize()
   위치: Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


-------------------------2------------------------
*** Error Report (Dispatcher) ***
KanColleViewer ver.4.5.0 rev.2
2018-09-20 오후 1:22:58 +09:00

SystemEnvironment
OS:           Microsoft Windows 8.1 Enterprise K
OSVersion:    6.3.9600
Architecture: 64비트
Runtime:      .NET Framework Version: 4.7.1

CPU:         Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
RAM (Total): 8,068,572 KB
RAM (Free):  5,175,696 KB

Sender:    System.Windows.Threading.Dispatcher
Exception: System.IO.FileNotFoundException

System.IO.FileNotFoundException: 파일이나 어셈블리 'CefSharp.Core.dll' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다.
파일 이름: 'CefSharp.Core.dll'
   위치: Grabacr07.KanColleViewer.Application.OnExit(ExitEventArgs e)
   위치: System.Windows.Application.DoShutdown()
   위치: System.Windows.Application.ShutdownImpl()
   위치: System.Windows.Application.ShutdownCallback(Object arg)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


-----------------3----------------
*** Error Report (Dispatcher) ***
KanColleViewer ver.4.5.0 rev.2
2018-09-20 오후 1:22:59 +09:00

SystemEnvironment
OS:           Microsoft Windows 8.1 Enterprise K
OSVersion:    6.3.9600
Architecture: 64비트
Runtime:      .NET Framework Version: 4.7.1

CPU:         Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
RAM (Total): 8,068,572 KB
RAM (Free):  5,168,132 KB

Sender:    System.Windows.Threading.Dispatcher
Exception: System.NullReferenceException

System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: Grabacr07.KanColleViewer.Application.ReportException(String caller, Object sender, Exception exception)
   위치: Grabacr07.KanColleViewer.Application.<>c.<OnStartup>b__13_0(Object sender, DispatcherUnhandledExceptionEventArgs args)
   위치: System.Windows.Threading.Dispatcher.CatchException(Exception e)
   위치: System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   위치: System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   위치: System.Windows.Threading.DispatcherOperation.InvokeImpl()
   위치: System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   위치: MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Windows.Threading.DispatcherOperation.Invoke()
   위치: System.Windows.Threading.Dispatcher.ProcessQueue()
   위치: System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------4---------------------
*** Error Report (AppDomain) ***
KanColleViewer ver.4.5.0 rev.2
2018-09-20 오후 1:23:00 +09:00

SystemEnvironment
OS:           Microsoft Windows 8.1 Enterprise K
OSVersion:    6.3.9600
Architecture: 64비트
Runtime:      .NET Framework Version: 4.7.1

CPU:         Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
RAM (Total): 8,068,572 KB
RAM (Free):  5,161,404 KB

Sender:    System.AppDomain
Exception: System.NullReferenceException

System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: Grabacr07.KanColleViewer.Application.ReportException(String caller, Object sender, Exception exception)
   위치: Grabacr07.KanColleViewer.Application.<>c.<OnStartup>b__13_0(Object sender, DispatcherUnhandledExceptionEventArgs args)
   위치: System.Windows.Threading.Dispatcher.CatchException(Exception e)
   위치: System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   위치: System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   위치: System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   위치: System.Windows.Application.RunDispatcher(Object ignore)
   위치: System.Windows.Application.RunInternal(Window window)
   위치: System.Windows.Application.Run(Window window)
   위치: Grabacr07.KanColleViewer.Application.Main()
 

이게 전부입니다

**Comment by WolfgangKurz** [comment]
Visual Studio 2015용 Visual C++ 재배포 가능 패키지 설치하셨나요?

**Comment by Xenon2000** [comment]
죄송합니다... 곧 클로즈 하겠습니다.
그 이전에...
주소창에 chrome-error://chromewebdata/ 만 나오고 링크를 직접붙여넣어도 접속이 안되네요.

**Comment by WolfgangKurz** [comment]
프로그램 종료 후
`%appdata%\..\Local\grabacr.net\KanColleViewer\Chromium`
폴더 삭제 후 다시 시작해도 동일한지 확인해주세요.

**Comment by Xenon2000** [comment]
동일합니다

**Comment by WolfgangKurz** [comment]
"게임시작!" 버튼도 동일한가요?

**Comment by Xenon2000** [comment]
동일합니다

**Comment by WolfgangKurz** [comment]
폴더에 debug.log 파일 있을텐데, 첨부해주세요.

내용 복사&붙여넣기 말고 깃허브 작성창에 드래그&드롭 혹은 파일을 붙여넣기 하시면 첨부됩니다.

**Comment by Xenon2000** [comment]
[debug.log](https://github.com/CirnoV/KanColleViewer/files/2399696/debug.log)

**Comment by WolfgangKurz** [comment]
WebGL 사용하기 위한 과정에서 오류가 발생하고 있어서 GPU 사용을 안하게 변경해보았습니다. (깡겜은 작동하는거 확인했습니다.)

아래 실행파일로 덮어쓴 후에 시도해보세요.

[KanColleViewer.zip](https://github.com/CirnoV/KanColleViewer/files/2399723/KanColleViewer.zip)

**Comment by Xenon2000** [comment]
그래도 동일합니다...ㅠㅠ

**Comment by WolfgangKurz** [comment]
설정의 네트워크 탭에서 프록시 설정은 안되어있죠?

**Comment by Xenon2000** [comment]
넵!

**Comment by WolfgangKurz** [comment]
> https://github.com/Grabacr07/KanColleViewer/issues/239

네트워크 탭의 "대기 포트 변경" 체크 되어있나요?

**Comment by Xenon2000** [comment]
체크안되어있습니다 채크 할까요?

**Comment by WolfgangKurz** [comment]
체크하고 포트 번호 37564로 변경해보시겠어요?
재시작 필요합니다.

**Comment by Xenon2000** [comment]
ㅠㅠ...
![bb](https://user-images.githubusercontent.com/42765988/45797685-c430dc00-bce1-11e8-99fe-53b89b113862.PNG)

**Comment by WolfgangKurz** [comment]
백신 등에 의해 일부 파일이 삭제되었을 가능성이 있을까요?

최신 릴리즈 파일로 시도해보셨나요?:

**Comment by Xenon2000** [comment]
이거... 받은지 얼마 안된거고 백신이 지운기록은 없습니다...

**Comment by WolfgangKurz** [comment]
로그만 봐서는 WebGL 기능 관련 작업을 하다가 오류가 발생하는 것으로 보이는데, 이것저것 확인해봐도 확실한 해결법이 보이지가 않네요.

일단은 계속 확인해보겠습니다.

**Comment by Xenon2000** [comment]
[debug.log](https://github.com/CirnoV/KanColleViewer/files/2399820/debug.log)

다시한번 올려봅니다... 아마 아까랑 다르지 않을까요...

**Comment by WolfgangKurz** [comment]
[KanColleViewer.zip](https://github.com/CirnoV/KanColleViewer/files/2399850/KanColleViewer.zip)

이 파일도 동일한지 확인 부탁드립니다.

**Comment by Xenon2000** [comment]
네...ㅠㅠ 뭐가뭔지 모르겠네요...
혹시 가능하시다면 팀뷰어로 봐주실수 있는지...ㅠㅠ

**Comment by WolfgangKurz** [comment]
그래픽 카드 없이 인텔 내장 그래픽 사용중인가요?

**Comment by Xenon2000** [comment]
네 내장그래픽 입니다.
i3-6100 이니까 HD530입니다

**Comment by WolfgangKurz** [comment]
[KanColleViewer.zip](https://github.com/CirnoV/KanColleViewer/files/2399981/KanColleViewer.zip)

이걸로 시도해보시고 debug.log 첨부해주세요,.

**Comment by Xenon2000** [comment]
[debug.log](https://github.com/CirnoV/KanColleViewer/files/2400010/debug.log)
첨부했습니다 확인부탁 드립니다.

**Comment by Xenon2000** [comment]
이 문제가 이유는 모르지만 동일 조건에서 현제는 발생하지 않고, 저 이외의 다른분들께 같은 이슈를 보지 못하였으니 이 이슈를 클로즈 하겠습니다
