### ISSUE TITLE
NullReferenceException from GCWorker.Dispose()

### ISSUE THREAD

**Issue by Gnbrkm41** [CirnoV/KanColleViewer#126]
```
응용 프로그램: KanColleViewer.exe
Framework 버전: v4.0.30319
설명: 처리되지 않은 예외로 인해 프로세스가 종료되었습니다.
예외 정보:System.NullReferenceException
   위치: Grabacr07.KanColleViewer.Models.GCWorker.Dispose()
   위치: Grabacr07.KanColleViewer.Models.GCWorker.Finalize()
```
https://github.com/CirnoV/KanColleViewer/blob/master/source/Grabacr07.KanColleViewer/Models/GCWorker.cs#L95
`GCThread?.Join();`으로 해결될 문제일까요?

**Comment by WolfgangKurz** [comment]
어차피 GC가 유용하게 쓰이는 기능도 아니고, 

일정 시간마다 Collect 할 때에 All 로 GC 하지 않게 바뀌면서 크게 의미가 없는 기능이 되었습니다.
(설정 페이지에서 직접 정리 버튼을 누를 때는 All 로 GC 하는 것으로 기억합니다.)

기능을 다시 지우면 되는데, 솔직히 손 놨습니다.

저는 더 이상의 개발을 하지 않을 생각입니다.
