### ISSUE TITLE
빌드 관련 질문

### ISSUE THREAD

**Issue by Gnbrkm41** [CirnoV/KanColleViewer#128]
빌드시 필요한 프로그램/SDK가 무엇이 있는지요? 비주얼 스튜디오 2019로 빌드 시도시 문제가 일부 있어서 어찌저찌 하다 성공은 했습니다만 직접 여쭈어보는 게 확실할 것 같아 물어봅니다.

* 깃 클라이언트가 서브모듈 업데이트시 실패함
```
$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object 3f671250fd42105002f9cd45b7a83eca2a8494d0
Fetched in submodule path 'source/MetroRadiance', but it did not contain 3f671250fd42105002f9cd45b7a83eca2a8494d0. Direct fetching of that commit failed.
```
* BattleInfoPlugin와 EventMapHpViewer 프로젝트가 존재하지 않음 (비주얼 스튜디오 솔루션 프로젝트 목록엔 존재하나 폴더가 존재하지 않아 로드에 실패함)
  * 별도의 리포지토리로 존재하는 것은 확인했습니다 (CirnoV/BattleInfoPlugin, CirnoV/EventMapHpViewer)
* 라이브러리 어셈블리 파일들은 수동으로 이동하나요? 빌드시 `/lib` 폴더가 아닌 빌드 출력 폴더 루트에 복사됩니다.
* 빌드 아키텍쳐는 AnyCPU가 아니라 x86 / x64로 지정해야 하나요? CefSharp 바이너리때문에 AnyCPU로 빌드하면 안 되는 것 같습니다.
* `source/Grabacr07.KanColleViewer/Application.Static.cs` 파일에서 `SystemEnvironment` 타입이 존재하지 않다며 오류가 발생합니다
  * MetroTrilithon 서브모듈이 커밋 https://github.com/CirnoV/KanColleViewer/commit/ab55d974742b5b62c1d5bf7a02558d6b4dc4c07f 에서 업데이트된 것 같으나 현재 해당 리포지토리에 가면 2016년을 마지막으로 변경된 것이 없습니다. 첫번째 오류와 관련이 있을까요?
* 빌드시 `Microsoft Expressions Blend 4 SDK`나 비주얼 스튜디오 2015가 필요한가요? `System.Windows.Interactivity`같은 일부 라이브러리가 존재하지 않다고 실패했으나 해당 두 요소 설치 후 더 이상 실패하지 않습니다.

이외에도 빌드시 필요로 한 설정 / 프로그램 / 기타 등이 있으면 알려주시면 감사하겠습니다.

**Comment by WolfgangKurz** [comment]
1. 일부 서브모듈은 제가 포크한 라이브러리가 이용됩니다. (WolfgangKurz/MetroTrilithon 등)
2. 해당 플러그인들은 CirnoV/BattleInfoPlugin, CirnoV/EventMapHpViewer 가 이용됩니다. 디렉토리에 맞게 clone 하여 구성해야합니다.
3. 수동으로 이동합니다.
4. AnyCPU 빌드 가능한 옵션을 넣어서 에러가 아닌 워닝으로 빌드가 되기는 하는데, 안된다면 x86으로 빌드하면 됩니다.
5. SystemEnvironment 타입은 오리지널 MetroTrilithon 에도 존재하는 타입입니다. 다시 확인해보시기 바랍니다.
6. 필요 없는걸로 압니다. 저도 2017 환경에서 개발했구요. 추가 설치해서 문제 없다면 그대로 개발하시면 될 것 같습니다.

그 외 조심할 사항은, 솔루션에 포함된 프로젝트들을 전부 불러와서 컴파일 할 수 있는 환경으로 유지하는 것과 Nuget 패키지 관리만 잘 해주면 될 것 같습니다.

**Comment by Gnbrkm41** [comment]
확인했습니다. 감사합니다.
