### ISSUE TITLE
야전 전투예보 기능 문제

### ISSUE THREAD

**Issue by ForteEscape** [CirnoV/KanColleViewer#69]
야전으로 진입할시에 전투예보 기능이 제대로 동작하지 않습니다.
![ffsfsdsd](https://user-images.githubusercontent.com/24915062/35897801-502d64ea-0c06-11e8-9ddc-b0a47615a8a3.png)

![fsfsdf](https://user-images.githubusercontent.com/24915062/35897789-46934012-0c06-11e8-8032-58c0bb548754.png)

![fsdfaf](https://user-images.githubusercontent.com/24915062/35897807-5bb37b10-0c06-11e8-8d3d-8a6d474c2498.png)

![asdfasdfsfsd](https://user-images.githubusercontent.com/24915062/35897813-663b21d2-0c06-11e8-8053-df3648259f85.png)

**Comment by WolfgangKurz** [comment]
야전 관련 문제들 수정중에 있습니다.

일이 바빠서 고치질 못하고 있네요.

2018. 2. 7. 오후 12:57에 "sehunkim" <notifications@github.com>님이 작성:

**Comment by ForteEscape** [comment]
언제나 수고 많으십니다

**Comment by ForteEscape** [comment]
이슈 하나를 더 열긴 그래서 여기서 물어보지만 함선 탭에 개조레벨과 함께 설계도가 필요할 시 설계도 아이콘이 들어가는데 나가나미의 경우 전투상보 아이콘을 추가해야하지 않을까요?

**Comment by WolfgangKurz** [comment]
네 그것도 수정할게요. 별도 이슈로 작성해주세요 잊어먹어요
