### ISSUE TITLE
유격사령부 퇴피 문제

### ISSUE THREAD

**Issue by ForteEscape** [CirnoV/KanColleViewer#81]
유격사령부를 이용하여 퇴피를 할 시 일반 사령부의 퇴피처럼 퇴피 마크가 생기지 않고 일반 대파시와 같은 동작(대파시 나오는 Toast등)을 보입니다.
아래는 퇴피시 뷰어입니다.

**Comment by ForteEscape** [comment]
![sdfsdfsfsfsfs](https://user-images.githubusercontent.com/24915062/36523160-a776212c-17e3-11e8-834c-1ba4a3faa9f2.png)

**Comment by WolfgangKurz** [comment]
유격사령부 쓸 때 확인하겠습니다.
아직 E-4 파밍을 못했어요
